---
name: 'Item Warehouse: API'
description: A warehouse with an API on the front of it
version: 2.4.0
slug: item_warehouse_api
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
options:
  database_username: warehouse_manager
  database_driver_name: mariadb+pymysql
  database_host: homeassistant.local
  database_port: 3306
  database_name: item_warehouse
schema:
  database_url: str?
  database_username: str?
  database_password: password?
  database_driver_name: str?
  database_host: str?
  database_port: int?
  database_name: str?
ports:
  8002/tcp: 8002
